language: php

dist: bionic

os: linux

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
    chrome: stable

jobs:
    include:
        -   php: '7.3'
            env: SYLIUS_VERSION=1.4.*

        -   php: '7.3'
            env: SYLIUS_VERSION=1.5.*

        -   php: '7.3'
            env: SYLIUS_VERSION=1.6.*

        -   php: '7.3'
            env: SYLIUS_VERSION=1.7.*

        -   php: '7.4'
            env: SYLIUS_VERSION=1.6.*

        -   php: '7.4'
            env: SYLIUS_VERSION=1.7.*

services:
  - mysql

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"
    - mkdir -p tests/Application/web/media/image

install:
    - composer require sylius/sylius:${SYLIUS_VERSION} --no-interaction --no-update
    - composer install --no-interaction --prefer-dist --no-suggest
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    - (cd tests/Application && bin/console assets:install public --env=test -vvv)
    - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
    - (cd tests/Application && yarn build)

    # Download Symfony CLI
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/symfony ]; then
            wget https://get.symfony.com/cli/installer -O - | bash
            mv ~/.symfony/bin/symfony $SYLIUS_CACHE_DIR
        fi
        php -v | head -n 1 | awk '{ print $2 }' > .php-version

    # Run Chrome Headless
    - google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &

    # Run webserver
    - (cd tests/Application && $SYLIUS_CACHE_DIR/symfony server:start --port=8080 --dir=public --daemon)

script:
    - composer validate --strict
    - composer analyse

    - vendor/bin/phpunit
    - vendor/bin/phpspec run
    - vendor/bin/behat --tags="~@javascript" --strict -vvv --no-interaction || vendor/bin/behat --tags="~@javascript" --strict -vvv --no-interaction --rerun
    - vendor/bin/behat --tags="@javascript" --strict -vvv --no-interaction || vendor/bin/behat --tags="@javascript" --strict -vvv --no-interaction --rerun

    -  (cd tests/Application && bin/console sylius:fixtures:load --no-interaction)

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
