sylius_mailer:
  emails:
    brille24_failed_price_import_csv:
      subject: 'brille24.email.customer_option_price_import_failed'
      template: "@Brille24SyliusCustomerOptionsPlugin/Email/failed_price_import_csv.html.twig"
    brille24_failed_price_import_product_list:
      subject: 'brille24.email.customer_option_price_import_failed'
      template: "@Brille24SyliusCustomerOptionsPlugin/Email/failed_price_import_product_list.html.twig"
